[node]
# You can select other gRPC endpoints from [the list](https://docs.dydx.exchange/infrastructure_providers-network/resources#full-node-endpoints).
endpoint = "http://dydx-dao-grpc-1.polkachu.com:23890"
chain_id = "dydx-mainnet-1"
fee_denom = "ibc/8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5"

[indexer]
http.endpoint = "https://indexer.dydx.trade"
ws.endpoint = "wss://indexer.dydx.trade/v4/ws"

[noble]
# Noble mainnet configuration
endpoint = "https://noble-grpc.polkachu.com:11890"
chain_id = "noble-1"
fee_denom = "uusdc"
gas_price = "0.025"
